#!/usr/bin/env bash

set -e

DEFAULT_CONFIG_PREFIX="default"
CONFIG_SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Ugly hack to force proper version of Python on CentOS 5.x systems.
python_bin=`which python`
if [ "$(python -V 2>&1 | cut -c8-10)" = "2.4" ]; then
  alt_python_bin="/usr/bin/python2.6"
  echo "Using alt Python ${alt_python_bin}"
  python_bin="${alt_python_bin}"
fi

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

for conf in ${DEFAULT_CONFIG_PREFIX} ${@}; do
    ${python_bin} "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "config/${conf}${CONFIG_SUFFIX}"
done
