# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

[status]
disabled = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Configure directory
[directory]
truncation_length = 5

# Configure Git branch
[git_branch]
symbol = ' '

# Configure Git metrics
[git_metrics]
disabled = false

# Configure AWS
[aws]
disabled = true

# Configure GCP
[gcloud]
disabled = true

# Configure Ruby
[ruby]
detect_variables = []

# Configure command duration
[cmd_duration]
format = '[⏱ $duration]($style) '
style = 'yellow'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
