- defaults:
    link:
      force: true
      relink: true

- clean: ['~']

- link:
    ~/.bash_completion.d/custom-server-tools.sh:
      create: true
      path: bash_completion.d/custom-server-tools.sh
    ~/.bash_completion.d/pssh:
      create: true
      path: bash_completion.d/pssh
    ~/.bash_completion.d/rebar:
      create: true
      path: bash_completion.d/rebar
    ~/.bash_completion.d/subversion:
      create: true
      path: bash_completion.d/subversion
    ~/.bash_completion.d/vit:
      create: true
      path: bash_completion.d/vit
    ~/.bash_completion.d/vagrant:
      create: true
      path: bash_completion.d/vagrant

    ~/.bashrc.d/android.sh:
      create: true
      path: bashrc.d/android.sh
    ~/.bashrc.d/apartment_lines.sh:
      create: true
      path: bashrc.d/apartment_lines.sh
    ~/.bashrc.d/awscli.sh:
      create: true
      path: bashrc.d/awscli.sh
    ~/.bashrc.d/bash-completion.sh:
      create: true
      path: bashrc.d/bash-completion.sh
    ~/.bashrc.d/brew-cask.sh:
      create: true
      path: bashrc.d/brew-cask.sh
    ~/.bashrc.d/colossus.sh:
      create: true
      path: bashrc.d/colossus.sh
    ~/.bashrc.d/fzf.sh:
      create: true
      path: bashrc.d/fzf.sh
    ~/.bashrc.d/go.sh:
      create: true
      path: bashrc.d/go.sh
    ~/.bashrc.d/jekyll.sh:
      create: true
      path: bashrc.d/jekyll.sh
    ~/.bashrc.d/luaver.sh:
      create: true
      path: bashrc.d/luaver.sh
    ~/.bashrc.d/linuxbrew.sh:
      create: true
      path: bashrc.d/linuxbrew.sh
    ~/.bashrc.d/nvm.sh:
      create: true
      path: bashrc.d/nvm.sh
    ~/.bashrc.d/openssl.sh:
      create: true
      path: bashrc.d/openssl.sh
    ~/.bashrc.d/packer.sh:
      create: true
      path: bashrc.d/packer.sh
    ~/.bashrc.d/pijaz.sh:
      create: true
      path: bashrc.d/pijaz.sh
    ~/.bashrc.d/poor-mans-vault.sh:
      create: true
      path: bashrc.d/poor-mans-vault.sh
    ~/.bashrc.d/pyenv.sh:
      create: true
      path: bashrc.d/pyenv.sh
    ~/.bashrc.d/rvm.sh:
      create: true
      path: bashrc.d/rvm.sh
    ~/.bashrc.d/short_prompt.sh:
      create: true
      path: bashrc.d/short_prompt.sh
    ~/.bashrc.d/ssh.sh:
      create: true
      path: bashrc.d/ssh.sh
    ~/.bashrc.d/stirlab.sh:
      create: true
      path: bashrc.d/stirlab.sh
    ~/.bashrc.d/terraform.sh:
      create: true
      path: bashrc.d/terraform.sh
    ~/.bashrc.d/vagrant.sh:
      create: true
      path: bashrc.d/vagrant.sh
    ~/.bashrc.d/vault.sh:
      create: true
      path: bashrc.d/vault.sh
    ~/.bashrc.d/vit.sh:
      create: true
      path: bashrc.d/vit.sh

    ~/.config/letsencrypt/cli.ini:
      create: true
      path: letsencrypt/cli.ini

    ~/.fscom_config:
    ~/.gvimrc:
    ~/.inputrc:
    ~/.kdiff3rc:
    ~/.minirc.cisco-console:
    ~/.my.cnf:
    ~/.rvmrc:
    ~/.siegerc:
    ~/.vimrc.local:

    ~/.ssh/authorized_keys:
      create: true
      path: ssh/authorized_keys
    ~/.ssh/config:
      create: true
      path: ssh/config

    ~/.taskrc:
    ~/.taskdebugrc:
    ~/.taskrc.d:
    ~/.tm_properties:

    ~/.vagrant.d/Vagrantfile:
      create: true
      path: vagrant.d/Vagrantfile

    ~/.vnc/config.d/vncviewer:
      create: true
      path: vnc/config.d/vncviewer
    ~/.vnc/identities:
      create: true
      path: vnc/identities

    ~/bin/al-s3-operations.sh:
      create: true
      path: bin/al-s3-operations.sh
    ~/bin/al-vagrant.sh:
      create: true
      path: bin/al-vagrant.sh

    ~/bin/btc-balance.sh:
      create: true
      path: bin/btc-balance.sh
    ~/bin/camera-reboot.sh:
      create: true
      path: bin/camera-reboot.sh
    ~/bin/chrome-ignore-certificate-errors.sh:
      create: true
      path: bin/chrome-ignore-certificate-errors.sh
    ~/bin/coffee.sh:
      create: true
      path: bin/coffee.sh
    ~/bin/deploy_pijaz_file:
      create: true
      path: bin/deploy_pijaz_file
    ~/bin/demux-video.sh:
      create: true
      path: bin/demux-video.sh
    ~/bin/file-media.sh:
      create: true
      path: bin/file-media.sh
    ~/bin/fix-git-dir-perms.sh:
      create: true
      path: bin/fix-git-dir-perms.sh
    ~/bin/home-backup.sh:
      create: true
      path: bin/home-backup.sh
    ~/bin/onenote_outline:
      create: true
      path: bin/onenote_outline
    ~/bin/onenote_todo:
      create: true
      path: bin/onenote_todo
    ~/bin/p:
      create: true
      path: bin/p
    ~/bin/power-profile.sh:
      create: true
      path: bin/power-profile.sh
    ~/bin/ppull:
      create: true
      path: bin/ppull
    ~/bin/pscp:
      create: true
      path: bin/pscp
    ~/bin/pssh:
      create: true
      path: bin/pssh
    ~/bin/pstat:
      create: true
      path: bin/pstat
    ~/bin/repo-force-new-hash.sh:
      create: true
      path: bin/repo-force-new-hash.sh
    ~/bin/repo-status.sh:
      create: true
      path: bin/repo-status.sh
    ~/bin/show-vagrant-configs:
      create: true
      path: bin/show-vagrant-configs
    ~/bin/slp:
      create: true
      path: bin/slp
    ~/bin/stop-test-servers.sh:
      create: true
      path: bin/stop-test-servers.sh
    ~/bin/store-media.sh:
      create: true
      path: bin/store-media.sh
    ~/bin/tw-move-project.sh:
      create: true
      path: bin/tw-move-project.sh
    ~/bin/video-backup.sh:
      create: true
      path: bin/video-backup.sh
    ~/bin/wcr:
      create: true
      path: bin/wcr
    ~/.vit/config.ini:
      create: true
      path: vit/config.ini
