- defaults:
    link:
      force: true
      relink: true

- clean: ['~']

- link:
    ~/.bashrc:
    ~/.bashrc.d/liquidprompt.sh:
      create: true
      path: bashrc.d/liquidprompt.sh
    ~/.config/liquidpromptrc:
      create: true
      path: liquidpromptrc
    ~/bin/cugrep:
      create: true
      path: bin/cugrep
    ~/bin/f:
      create: true
      path: bin/f
    ~/bin/gugrep:
      create: true
      path: bin/gugrep
    ~/bin/ix:
      create: true
      path: bin/ix
    ~/bin/speedtest:
      create: true
      path: bin/speedtest
    ~/.colordiffrc:
    ~/.curlrc:
    ~/.gitconfig:
    ~/.gitignore:
    ~/.git-repositories:
    ~/.liquidprompt.ps1:
    ~/.tmux.conf:
    ~/.vim/autoload/pathogen.vim:
      create: true
      path: vim/autoload/pathogen.vim
    ~/.vimrc:
