- defaults:
    link:
      force: true
      relink: true

- clean: ['~']

- link:
    ~/.bashrc:
    ~/.bashrc.d/liquidprompt.sh:
      create: true
      path: bashrc.d/liquidprompt.sh
    ~/.bashrc.d/salt.sh:
      create: true
      path: bashrc.d/salt.sh
    ~/bin/cugrep:
      create: true
      path: bin/cugrep
    ~/bin/f:
      create: true
      path: bin/f
    ~/bin/gugrep:
      create: true
      path: bin/gugrep
    ~/bin/ix:
      create: true
      path: bin/ix
    ~/.colordiffrc:
    ~/.curlrc:
    ~/.gitconfig:
    ~/.gitignore:
    ~/.git-repositories:
    ~/.liquidprompt.ps1:
    ~/.liquidpromptrc:
    ~/.sqliterc:
    ~/.tmux.conf:
    ~/.vim/autoload/pathogen.vim:
      create: true
      path: vim/autoload/pathogen.vim
    ~/.vim/bundle/icinga2:
      create: true
      path: vim/bundle/icinga2
    ~/.vimrc:
